optimizer:
    Adam:
        learning_rate: 1e-5
    warmup_steps: 5000

# Training options
train:
    epochs: 3
    log_step: 1
    batch_size: 8 # training batch size
    n_jobs: 30
    freeze_bert: False

# Evaluation options
eval:
    batch_size: 8 # used for dev/test splits
    n_jobs: 30
    size: 0.01 # validation data portion

dataset:
    train_data: /tmp2/py/data/fever/train.jsonl
    dev_data: /tmp2/py/data/fever/dev.jsonl
    small_wiki: data/small_wiki.json
    docs_sentence: /tmp2/py/data/fever/docs_sentence.pkl
    full_wiki: /tmp2/py/data/full_wiki.json
    full_docs_sentence: /tmp2/py/data/fever/full_docs_sentence.pkl
    full_docs_sentence_similarity: /tmp2/py/data/fever/full_docs_sentence_similarity.pkl

others:
    seed: 1009
    device_id: 0 # cpu: -1, gpu > 0
